### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by gaurav341** [Microsoft/angular2-slickgrid#13]
When run `gulp build`, following error display

    gulpInst.start.apply(gulpInst, toRun);
                  ^

> TypeError: Cannot read property 'apply' of undefined
>     at C:\Users\HP\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:393:7)
>     at startup (bootstrap_node.js:150:9)
>     at bootstrap_node.js:508:3

**Comment by kevcunnane** [comment]
@gaurav341 this looks like an issue with gulp. it's not finding its own exports. Looking at my computer, I have gulp-cli globally installed and it includes this (and works fine). I'd recommend installing the latest gulp-cli globally. We have instructions on installing gulp in our other repository, see the gulp section in https://github.com/Microsoft/vscode-mssql/wiki/contributing for details. I think this should resolve the issue

**Comment by andulv** [comment]
A comment here solved the issue for me: https://github.com/gulpjs/gulp-cli/issues/84
Run local gulp cli:
node ./node_modules/gulp/bin/gulp.js build
node ./node_modules/gulp/bin/gulp.js serve

**Comment by paritosh64ce** [comment]
I was also facing the same issue

> 
>    gulpInst.start.apply(gulpInst, toRun);
>                   ^
> TypeError: Cannot read property 'apply' of undefined
>     at C:\Users\Paritosh.Patel\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Solved it by installing `gulp-cli` before doing `gulp build` 
[gulpInst.start.apply(gulpInst, toRun); TypeError: Cannot read property 'apply' of undefined](https://github.com/gulpjs/gulp-cli/issues/84)

Can anyone please update `README` file?

**Comment by kevcunnane** [comment]
@paritosh64ce will do (PR is out now). By the way, we're open to contributions so if you find future issues, a fork & PR is very welcome :)
