### ISSUE TITLE
onSelectedRowsChanged() and getSelectedRows() not exposed

### ISSUE THREAD

**Issue by adamci** [Microsoft/angular2-slickgrid#5]
The JavaScript slickgrid class exposes an event emitter, `onSelectedRowsChanged`, that is the library's only available callback for row selection events. It appears that this property is not exposed through the SlickGrid Angular component.

One possible (but not so beautiful) workaround is to access the class with `@ViewChild` and then cast away the TypeScript errors with `any`:
```TypeScript
@ViewChild(SlickGrid) private slickGrid: SlickGrid;
(this.slickGrid as any)._grid.onSelectedRowsChanged.subscribe(() => {
});
```

Is there a better workaround, or does the callback need to be ported from the JavaScript library?

**Comment by coquagli** [comment]
I think the best solution is to port the callback. I can handle that.

**Comment by anthonydresser** [comment]
It certainly is _a_ solution. But you won't get any nice TS features doing that since slickgrid doesn't having typings. Another way, since this project is technically supposed to be a wrapper, is expose specific getters in the actual TS class that have corresponding types defined and then just call into the grid object for the actual property.

**Comment by coquagli** [comment]
@anthonydresser That was my original thought as well. But since the slickgrid API is fairly large, I would like to potentially avoid the scenario where we are frequently making changes to this repo to add wrapper functions based on user requests.

**Comment by anthonydresser** [comment]
@coquagli This repo is open source, although owned by the tools team. If people have feature requests that the team doesn't have the bandwidth for, they can always send PR's 😄 . But just straight up exposing the _grid object basically breaks the concept of a wrapper. @kevcunnane @kburtram thoughts?

**Comment by coquagli** [comment]
@coquagli Agreed. I think the best course of action would be to make the getter wrapper as you suggested.

**Comment by anthonydresser** [comment]
Perhaps a note on the read-me stating this is in an incomplete state is necessary.
